Disp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Disp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'dispetchers.views.show_orders', name="index"),
    # url(r'createorder/$', 'dispetchers.views.create_order', name="create_order"),
    # url(r'addoffer/$', 'dispetchers.views.add_offer', name="add_offer"),
    # url(r'addworker/$', 'dispetchers.views.add_worker', name="add_worker"),
    # url(r'^add_order_class/$', OrderCreateView.as_view(), name="add_order_class"),
    url(r'^create_order_detail/$', 'dispetchers.views.create_order_detail', name='create_order_detail'),
    url(r'edit_order/(?P<order_id>\d+)/$', 'dispetchers.views.edit_order', name='edit_order'),
    url(r'^admin/', include(admin.site.urls)),
)

dispetchers/models.py
# encoding=utf8
from django.db import models
from django.utils import timezone
from datetime import datetime

ORDERSTATUS = (
    ('NEW', 'Новая'),
    ('SET', 'Назначена'),
    ('INPROGRESS', 'В работе'),
    ('COMPLETED', 'Выполнена'),
)

# Create your models here.
class Category(models.Model):
    '''Categories for offers'''
    CategoryName = models.CharField(max_length=30, verbose_name='Имя категории')
    def __unicode__(self):
        return self.CategoryName
    def __str__(self):
        return self.CategoryName
    class Meta:
        verbose_name_plural = 'Категории'

class Offer(models.Model):
    '''Offers'''
    OfferName = models.CharField(max_length=150, verbose_name='Название услуги')
    OfferCategory = models.ForeignKey(Category, verbose_name='Категория')
    OfferPrice = models.FloatField(verbose_name='Стоимость')
    Duration = models.FloatField(verbose_name='Базовая длительность', null=True, default=1.0)
    def __unicode__(self):
        return self.OfferCategory.CategoryName + ':' + self.OfferName + '   ' + str(self.OfferPrice)
    def __str__(self):
        return self.OfferCategory.CategoryName + ':' + self.OfferName + '   ' + str(self.OfferPrice)
    class Meta:
        verbose_name_plural = 'Услуги'


class Order(models.Model):
    '''Orders'''
    ClientName = models.CharField(max_length=150, verbose_name='Имя клиента')
    ClientAddress = models.CharField(max_length=200, verbose_name='Адрес клиента')
    PrefferedTime = models.DateTimeField(default=datetime.now(), verbose_name='Предпочетаемое время')
    CreateTime = models.DateTimeField(default=datetime.now(), verbose_name='Дата создания')
    FactTime = models.DateTimeField(null=True, blank=True, verbose_name='Фактическое время')
    PlanTotalSumm = models.FloatField(verbose_name='Плановая стоимость', null=True)
    FactTotalSumm = models.FloatField(verbose_name='Фактическая стоимость', null=True)
    Status = models.CharField(max_length=15, choices=ORDERSTATUS, default='New', verbose_name='Статус')
    def __unicode__(self):
        return self.ClientName
    def __str__(self):
        return self.ClientName
    class Meta:
        verbose_name_plural = 'Заявки'
        get_latest_by = "CreateTime"

class Worker(models.Model):
    '''Workers'''
    FirstName = models.CharField(max_length=30, verbose_name='Имя')
    LastName = models.CharField(max_length=50, verbose_name='Фамилия')
    WorkerCategory = models.ForeignKey(Category, verbose_name='Категория')
    # IsBusy = models.BooleanField(default=False, verbose_name='Занят')
    # BusyStartTime = models.DateTimeField(blank=True, null=True)
    # BusyEndTime = mo
    IsChief = models.BooleanField(default=False, verbose_name='Бригадир')
    Orders = models.ManyToManyField(Order, verbose_name='Заявки', null=True, blank=True)
    def __unicode__(self):
        return self.WorkerCategory.CategoryName + ':' + self.LastName + ' ' + self.FirstName
    def __str__(self):
        return self.WorkerCategory.CategoryName + ':' + self.LastName + ' ' + self.FirstName
    class Meta:
        verbose_name_plural = 'Рабочие'

class OrderOfferDetail(models.Model):
    OrderName = models.ForeignKey(Order, null=True)
    OfferName = models.ForeignKey(Offer, null=True, verbose_name='Услуга')
    Worker = models.ForeignKey(Worker, null=True, verbose_name='Рабочий')
    FactWorkedHours= models.TimeField(null=True, blank=True, verbose_name='Фактические часы')
    Comments = models.TextField(null=True, blank=True, verbose_name='Комментарии')
    def __str__(self):
        return self.OfferName
    def __unicode__(self):
        return unicode(self.OfferName)
    class Meta:
        verbose_name_plural = 'Детали заявки'

class WorkerHours(models.Model):
    '''Worker's busy hours'''
    worker = models.ForeignKey(Worker)
    busyStartTime = models.DateTimeField(null=True)
    busyEndTime = models.DateTimeField(null=True)

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Система обработки заявок {% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/create_order_detail.html
{% extends "base.html" %}
{% block title %}Test formset{% endblock %}
{% block content %}
{% if order_form %}
    <form action="." method="post">
        {% csrf_token %}
        {{ orderdetail_formset.management_form }}
        <table>
            {{ order_form.as_table }}
            {% include "widgets/orderofferdetail.html" %}
{#            {% for form in orderdetail_formset.forms %}#}
{#                <table>{{ form }}</table>#}
{#            {% endfor %}#}
        </table>
        <p><input type="submit" value="Submit!" /></p>
    </form>
{% endif %}
{% for error in orderdetail_formset.errors %}
    {{ error }}
{% endfor %}
<br>
    {{ orderdetail_formset.non_form_errors }}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %} Главная {% endblock %}
{% block content %}
<table border="1" bordercolor="#008b8b" bgcolor="#008b8b">
<tr>
    <td><a href="{% url "create_order_detail" %}"><h2>Создать заявку</h2></a> </td>
</tr>
</table>
<table border="1" bordercolor="black">
    <tr>
        <td>#</td>
        <td>Клиент</td>
        <td>Дата создания</td>
        <td>Статус</td>
        <td>Плановая сумма</td>
        <td>Фактическая сумма</td>
    </tr>
    {% for order in orders%}
        <tr>
            <td>{{ order.pk }}</td>
            <td><a href="{% url "edit_order" order_id=order.pk %}">{{ order.ClientName }}</a></td>
            <td>{{ order.CreateTime }}</td>
            <td>{{ order.get_Status_display }}</td>
            <td>{{ order.PlanTotalSumm }}</td>
            <td>{{ order.FactTotalSumm }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}